#!/bin/sh

:<<DOCUMENTATION

	Description:	Updates the local ports tree from the current quarterly SVN branch.
	Author:			Chris Wells (https://chriswells.io)

DOCUMENTATION


# Modify these variables if you use a different SVN branch or repo. -- cwells
BRANCH=$(svnlite ls https://svn.freebsd.org/ports/branches/ | sed -ne '/^20[0-9]\{2\}Q[1-4]/s|/$||p' | tail -1)
URL="https://svn.freebsd.org/ports/branches/$BRANCH"

# If a parameter was passed, use it as the destination directory.  For example,
# to update the ezjail ports tree: portsfetch /usr/jails/basejail/usr/ports
if [ -n "$1" ]; then
	DESTDIR="$1"
else
	DESTDIR=/usr/ports
fi

# Require root in order to write to the ports dir. -- cwells
if [ "$(id -u)" != "0" ]; then
	echo 'This script must be run as root or using sudo.' 1>&2
	exit 1
fi

# Validate variables before proceeding. -- cwells
if [ ! -d "$DESTDIR" ]; then
	echo 'Destination directory not found.'
	exit 1
elif [ "${#BRANCH}" != "6" ]; then
	echo 'Failed to determine the correct branch to use.'
	exit 1
fi

# Clear the contents of the destination directory if it's not being managed by SVN. -- cwells
if [ ! -z "$(ls -qAL -- "$DESTDIR")" ] && [ ! -d "$DESTDIR/.svn" ]; then
	echo 'Destination directory contains files but is not an SVN branch.'
	echo 'You must delete the existing files to switch to a quarterly branch.'
	# shellcheck disable=SC2039
	read -r -p "Do you want to delete the contents of \"$DESTDIR\"? [y/N]: " DELETE_FILES
	case $DELETE_FILES in
		[Yy]* ) find "$DESTDIR" -mindepth 1 -delete ;; # Delete all files in the dir. -- cwells
		* ) portsnap fetch update; exit 0 ;; # Use portsnap to update from HEAD. -- cwells
	esac
	echo ''
fi

if [ -d "$DESTDIR/.svn" ]; then # Destination directory is already managed by SVN. -- cwells
	if [ "$(svnlite info "$DESTDIR" | sed -ne 's/^URL: \(.*\)$/\1/p')" = "$URL" ]; then # Just update. -- cwells
		svnlite update "$DESTDIR"
	else # Switch to the current quarterly branch. -- cwells
		echo "Switching to the $BRANCH branch..."
		svnlite switch "$URL" "$DESTDIR"
	fi
else # Perform a fresh checkout of the current quarterly branch. -- cwells
	echo "Checking out a fresh copy of the $BRANCH branch..."
	svnlite checkout "$URL" "$DESTDIR"
fi


exit 0
