#!/bin/sh

:<<DOCUMENTATION

	Description:	Updates the local ports tree from the current quarterly Git branch.
	Author:			Chris Wells (https://chriswells.io)

DOCUMENTATION


REPO_URL="https://git.freebsd.org/ports.git"

# Require root in order to write to the ports dir. -- cwells
if [ "$(id -u)" != "0" ]; then
	echo 'This script must be run as root or using sudo.' 1>&2
	exit 1
fi

if ! which git > /dev/null; then
	pkg install git
fi

# If a parameter was passed, use it as the destination directory.  For example,
# to update the ezjail ports tree: portsfetch /usr/jails/basejail/usr/ports
if [ -n "$1" ]; then
	DESTDIR="$1"
else
	DESTDIR=/usr/ports
fi

if [ ! -d "${DESTDIR}" ]; then
	mkdir "${DESTDIR}"
fi

# Clear the contents of the destination directory if it's not being managed by Git. -- cwells
if [ ! -z "$(ls -qAL -- "${DESTDIR}")" ] && [ ! -d "${DESTDIR}/.git" ]; then
	echo 'Destination directory contains files but is not a Git repo.'
	echo 'You must delete the existing files to switch to a quarterly branch.'
	# shellcheck disable=SC2039
	read -r -p "Do you want to delete the contents of \"${DESTDIR}\"? [y/N]: " DELETE_FILES
	case $DELETE_FILES in
		[Yy]* ) find "${DESTDIR}" -mindepth 1 -delete ;; # Delete all files in the dir. -- cwells
		* ) portsnap fetch update; exit 0 ;; # Use portsnap to update from HEAD. -- cwells
	esac
	echo ''
fi

FRESH_CLONE=false
if [ ! -d "${DESTDIR}/.git" ]; then # Initial clone of the repo. -- cwells
	git clone "${REPO_URL}" "${DESTDIR}"
	FRESH_CLONE=true
fi

BRANCH=$(git -C "${DESTDIR}" branch --list -r | grep -E '^\s*origin/20[0-9]{2}Q[1-4]$' | sort | tail -1 | sed 's/ *origin\///')
if [ "${#BRANCH}" != "6" ]; then
	echo 'Failed to determine the correct branch to use.'
	exit 1
fi

if [ "$(git -C "${DESTDIR}" branch --show-current)" != "${BRANCH}" ]; then
	git -C "${DESTDIR}" checkout "${BRANCH}"
fi

if [ "${FRESH_CLONE}" = 'false' ]; then
	git -C "${DESTDIR}" pull --ff-only
fi

exit 0
